sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_8acaa5b479ff_key -iv $encrypted_8acaa5b479ff_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components udpate kubectl
  - gcloud auth activate-service-account --key-file service-account.json
